
name: web_view_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_downloader: ^1.11.1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.4
  flutter_svg: ^2.0.4
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  intl: ^0.17.0
  url_launcher: ^6.1.12
  flutter_widget_from_html: ^0.10.0
  share_plus: ^4.0.6
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  octo_image: ^1.0.2
  cached_network_image: ^3.2.1
  firebase_messaging: ^12.0.3
  firebase_analytics: ^9.3.2
  firebase_core: ^1.21.0
  store_redirect: ^2.0.1
  firebase_core_platform_interface: 4.5.1
  animated_floating_buttons: ^0.0.2
  file_picker: ^5.2.4
  awesome_dialog: ^3.0.2
  connectivity_plus: ^2.3.6+1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  gallery_saver: ^2.3.2
  dio: ^5.0.1
  image_picker: ^0.8.6+1
  flutter_local_notifications: ^13.0.0
  permission_handler: ^10.2.0
  image_gallery_saver: ^2.0.3
  #google_nav_bar: ^5.0.6
  google_mobile_ads: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  uni_links: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/



